<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ChangeListManager">
    <list default="true" id="5fa97f5a-b899-4e87-a4bd-c505f356aa96" name="Changes" comment="" />
    <option name="SHOW_DIALOG" value="false" />
    <option name="HIGHLIGHT_CONFLICTS" value="true" />
    <option name="HIGHLIGHT_NON_ACTIVE_CHANGELIST" value="false" />
    <option name="LAST_RESOLUTION" value="IGNORE" />
  </component>
  <component name="FileTemplateManagerImpl">
    <option name="RECENT_TEMPLATES">
      <list>
        <option value="Class" />
        <option value="JUnit5 Test Class" />
      </list>
    </option>
  </component>
  <component name="ProjectColorInfo">{
  &quot;associatedIndex&quot;: 6
}</component>
  <component name="ProjectId" id="3B7yAHLITKC1VqwiiDqP8P3H8eV" />
  <component name="ProjectViewState">
    <option name="hideEmptyMiddlePackages" value="true" />
    <option name="showLibraryContents" value="true" />
  </component>
  <component name="PropertiesComponent">{
  &quot;keyToString&quot;: {
    &quot;Application.TestGeometricObject.executor&quot;: &quot;Run&quot;,
    &quot;Application.TestResizable.executor&quot;: &quot;Run&quot;,
    &quot;ModuleVcsDetector.initialDetectionPerformed&quot;: &quot;true&quot;,
    &quot;RunOnceActivity.ShowReadmeOnStart&quot;: &quot;true&quot;,
    &quot;RunOnceActivity.typescript.service.memoryLimit.init&quot;: &quot;true&quot;,
    &quot;com.intellij.testIntegration.createTest.CreateTestDialog.defaultLibrary&quot;: &quot;JUnit5&quot;,
    &quot;com.intellij.testIntegration.createTest.CreateTestDialog.defaultLibrarySuperClass.JUnit5&quot;: &quot;&quot;,
    &quot;kotlin-language-version-configured&quot;: &quot;true&quot;,
    &quot;last_opened_file_path&quot;: &quot;C:/Users/marco/OneDrive/Desktop/MARCOS 2/UNIVERSIDAD/PRIMERO/2º Cuatrimestre/Metodología de la programación/Cuaderno 4/src&quot;,
    &quot;onboarding.tips.debug.path&quot;: &quot;C:/Users/marco/OneDrive/Desktop/MARCOS 2/UNIVERSIDAD/PRIMERO/2º Cuatrimestre/Metodología de la programación/Cuaderno 4/src/Main.java&quot;,
    &quot;vue.rearranger.settings.migration&quot;: &quot;true&quot;
  }
}</component>
  <component name="RecentsManager">
    <key name="CopyFile.RECENT_KEYS">
      <recent name="C:\Users\marco\OneDrive\Desktop\MARCOS 2\UNIVERSIDAD\PRIMERO\2º Cuatrimestre\Metodología de la programación\Cuaderno 4\src" />
      <recent name="C:\Users\marco\OneDrive\Desktop\MARCOS 2\UNIVERSIDAD\PRIMERO\2º Cuatrimestre\Metodología de la programación\Cuaderno 4\src\Cuaderno4\Ejercicio6\seis" />
      <recent name="C:\Users\marco\OneDrive\Desktop\MARCOS 2\UNIVERSIDAD\PRIMERO\2º Cuatrimestre\Metodología de la programación\Cuaderno 4\src\Cuaderno4\Ejercicio6\dos" />
    </key>
    <key name="CreateTestDialog.Recents.Supers">
      <recent name="" />
    </key>
    <key name="CreateTestDialog.RecentsKey">
      <recent name="Cuaderno4.Ejercicio6.cinco" />
    </key>
    <key name="CopyClassDialog.RECENTS_KEY">
      <recent name="Cuaderno4.Ejercicio6.seis" />
      <recent name="Cuaderno4.Ejercicio6.cinco" />
      <recent name="Cuaderno4.Ejercicio6.cuatro" />
      <recent name="Cuaderno4.Ejercicio6.tres" />
      <recent name="Cuaderno4.Ejercicio6.dos" />
    </key>
  </component>
  <component name="SharedIndexes">
    <attachedChunks>
      <set>
        <option value="bundled-jdk-30f59d01ecdd-2fc7cc6b9a17-intellij.indexing.shared.core-IU-253.31033.145" />
        <option value="bundled-js-predefined-d6986cc7102b-9b0f141eb926-JavaScript-IU-253.31033.145" />
      </set>
    </attachedChunks>
  </component>
  <component name="TaskManager">
    <task active="true" id="Default" summary="Default task">
      <changelist id="5fa97f5a-b899-4e87-a4bd-c505f356aa96" name="Changes" comment="" />
      <created>1773854257874</created>
      <option name="number" value="Default" />
      <option name="presentableId" value="Default" />
      <updated>1773854257874</updated>
      <workItem from="1773854261049" duration="4894000" />
      <workItem from="1773859921293" duration="1386000" />
      <workItem from="1773862601899" duration="15000" />
    </task>
    <servers />
  </component>
  <component name="TypeScriptGeneratedFilesManager">
    <option name="version" value="3" />
  </component>
</project>